import AppKit
import CryptoKit
import Observation

@Observable
@MainActor
final class ClipboardMonitor {
    private static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private var workspaceObservers: [NSObjectProtocol] = []
    private var isAsleep = false

    var suppressUntilChangeCount: Int = -1
    private(set) var isPaused = false

    init() {
        lastChangeCount = pasteboard.changeCount

        let center = NSWorkspace.shared.notificationCenter
        workspaceObservers = [
            center.addObserver(forName: NSWorkspace.willSleepNotification,
                              object: nil, queue: .main) { [weak self] _ in
                MainActor.assumeIsolated { self?.handleWillSleep() }
            },
            center.addObserver(forName: NSWorkspace.didWakeNotification,
                              object: nil, queue: .main) { [weak self] _ in
                MainActor.assumeIsolated { self?.handleDidWake() }
            }
        ]
    }

    func start() {
        timer?.invalidate()
        let t = Timer(timeInterval: 0.2, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() { timer?.invalidate(); timer = nil }

    func togglePause() { isPaused.toggle() }

    /// Captures anything on the pasteboard the timer has not seen yet. The
    /// timer only looks every 0.2s, which is long enough for a copy followed
    /// by an immediate summon-and-paste to beat it: the bar would open with
    /// the previous clip selected, paste that, and its own pasteboard write
    /// would bury the fresh copy before it was ever captured. Callers poll
    /// here before reading the selection or overwriting the pasteboard.
    func pollNow() { poll() }

    private func poll() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current
        guard !isAsleep || !Settings.shared.pauseClipboardCaptureDuringSleep else { return }
        guard !isPaused else { return }
        if current == suppressUntilChangeCount { return }
        guard let item = makeItem() else { return }
        // Stack entries must point at the canonical history item. A duplicate
        // capture can reuse an existing item (and discard a temporary image),
        // so stacking the raw capture would leave an invalid preview behind.
        let storedItem = ClipboardStore.shared.addCaptured(item)
        AppController.shared.capturePasteStackItem(storedItem)
    }

    private func handleWillSleep() {
        guard Settings.shared.pauseClipboardCaptureDuringSleep else { return }
        isAsleep = true
    }

    private func handleDidWake() {
        guard isAsleep else { return }
        isAsleep = false
        // Discard changes that happened while the Mac was asleep rather than
        // importing a stale clipboard value on the first post-wake poll.
        lastChangeCount = pasteboard.changeCount
    }

    /// Every file in a multi-file copy, not just the first. Some sources put
    /// each file in its own pasteboard item, others only fill the legacy
    /// filenames array and leave a single URL item behind — reading both and
    /// keeping the longer list captures the whole selection either way.
    private func copiedFileURLs() -> [URL]? {
        let fromItems = (pasteboard.readObjects(forClasses: [NSURL.self],
                                                options: [.urlReadingFileURLsOnly: true]) as? [URL]) ?? []
        let legacy = pasteboard.propertyList(forType: NSPasteboard.PasteboardType("NSFilenamesPboardType"))
        let fromFilenames = (legacy as? [String])?.map { URL(fileURLWithPath: $0) } ?? []
        let urls = fromFilenames.count > fromItems.count ? fromFilenames : fromItems
        return urls.isEmpty ? nil : urls
    }

    private func makeItem() -> ClipItem? {
        let types = pasteboard.types ?? []

        if types.contains(NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")) { return nil }
        if types.contains(NSPasteboard.PasteboardType("org.nspasteboard.TransientType")) { return nil }
        if Settings.shared.ignoreConcealed,
           types.contains(NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")) { return nil }

        let declaredSourceID = pasteboard.string(forType: Self.sourceType)
            .flatMap { $0.isEmpty ? nil : $0 }
        let front = NSWorkspace.shared.frontmostApplication
        let src: NSRunningApplication?
        if front == nil || front?.bundleIdentifier == Bundle.main.bundleIdentifier {
            src = AppController.shared.lastActiveApp
        } else {
            src = front
        }
        // Clipboard managers can set this standard marker when they put an item
        // back on the pasteboard. Prefer it to the foreground app, which is often
        // the clipboard manager itself and otherwise yields a generic icon.
        let bundleID = declaredSourceID ?? src?.bundleIdentifier
        let appName = declaredSourceID.flatMap { applicationName(forBundleID: $0) } ?? src?.localizedName
        guard !Settings.shared.isIgnoringSourceApp(bundleID) else { return nil }

        func decorate(_ item: inout ClipItem) {
            item.sourceBundleID = bundleID
            item.sourceAppName = appName
            item.sourceDeviceName = Host.current().localizedName
        }

        if let urls = copiedFileURLs(), !urls.isEmpty {
            var item = ClipItem(type: .file,
                                text: urls.map(\.lastPathComponent).joined(separator: ", "),
                                fileURLs: urls.map(\.absoluteString))
            decorate(&item)
            return item
        }

        if types.contains(.png) || types.contains(.tiff) {
            if let data = pngData() {
                let hash = Self.sha256Hex(data)
                guard let name = ClipboardStore.shared.storeImageData(data) else { return nil }
                var item = ClipItem(type: .image, imageFileName: name, imageHash: hash)
                decorate(&item)
                return item
            }
        }

        let rtf = pasteboard.data(forType: .rtf)
        // Browsers often provide HTML with no RTF; keep it for the Markdown
        // and Clean Formatting paste conversions without changing how the
        // clip is classified.
        let html = pasteboard.data(forType: .html)
        if let string = pasteboard.string(forType: .string), !string.isEmpty {
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            let type: ClipType
            if rtf != nil {
                type = .richText
            } else if isLink(trimmed) {
                type = .link
            } else {
                type = .text
            }
            var item = ClipItem(type: type, text: string, rtfData: rtf, htmlData: html)
            decorate(&item)
            return item
        }

        if hasColorType(types), let color = NSColor(from: pasteboard) {
            var item = ClipItem(type: .color, colorHex: color.usingColorSpace(.sRGB)?.hexString)
            decorate(&item)
            return item
        }

        return nil
    }

    private func hasColorType(_ types: [NSPasteboard.PasteboardType]) -> Bool {
        types.contains { $0.rawValue.localizedCaseInsensitiveContains("color") }
    }

    private func applicationName(forBundleID bundleID: String) -> String? {
        guard let url = NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleID) else { return nil }
        return Bundle(url: url)?.object(forInfoDictionaryKey: "CFBundleDisplayName") as? String
            ?? Bundle(url: url)?.object(forInfoDictionaryKey: "CFBundleName") as? String
    }

    private static func sha256Hex(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    private func pngData() -> Data? {
        if let data = pasteboard.data(forType: .png) { return data }
        guard let tiff = pasteboard.data(forType: .tiff),
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    private func isLink(_ s: String) -> Bool {
        guard !s.contains(" "), !s.contains("\n"),
              let url = URL(string: s),
              let scheme = url.scheme?.lowercased(),
              ["http", "https"].contains(scheme),
              url.host != nil else { return false }
        return true
    }
}

private extension NSColor {
    convenience init?(from pasteboard: NSPasteboard) {
        guard let objs = pasteboard.readObjects(forClasses: [NSColor.self], options: nil) as? [NSColor],
              let c = objs.first else { return nil }
        self.init(cgColor: c.cgColor)
    }
}
